all: ruptimeClient ruptimeServer

ruptimeClient: ruptimeClient.c
	gcc -o ruptimeClient ruptimeClient.c

ruptimeServer: ruptimeServer.c
	gcc -o ruptimeServer ruptimeServer.c

clean:
	rm ruptimeClient ruptimeServer